### ISSUE TITLE
Project Environment setup

### ISSUE THREAD

**Issue by ffriday** [ffriday/graphiql-app#1]
### Tasks:
- [x] Creating a repository
- [x] React project setup (linter, tests, etc.)
- [x] CI/CD setup [Netlify / Vercel] + Github Actions
- [x] Choosing workflow strategy
- [x] Choosing styles approach (css/sass/tailwind/other)
### Planning:
- Project technologies review (Firebase, GraphiQL)
- Task assignment and deadline setting
#### Possible task directions:
- View (interface)
    - Welcome page
    - User auth
    - GraphiQL page with:
        - request editor (query editor / JSON viewer)
        - variables editor
        - headers editor
        - documentation explorer (should be lazy-loaded)
        - response section (query editor / JSON viewer)
        - possibility to change to a different user-specified API endpoint
- Localization (EN/RU, Context api)
- Routing (React-router)
- Code prettyfying and parsing
- Client-server interactions
    - Request schema (React Query)
    - Send and receive data from API (React Query)
- Authentication
    - Server-side (Fireabse)
    - Client-side
- Proxy for CORS [optional]
- Tests (Vitest, React-testing-library)

### Materials:
[Public GraphQL APIs](https://github.com/graphql-kit/graphql-apis)
