### ISSUE TITLE
Localization (translation) fix

### ISSUE THREAD

**Issue by ffriday** [ffriday/graphiql-app#7]
### Subject
Change translation to useTranslate custom hook.

### Description:
It is not very clear why we have a file named `LangProvider.tsx` with the `AppContext` in it:) 
I think we need to create a dedicated context for translation since it's a standalone functionality.

Nice job on adding translations, but this approach might get out of hand at some point since we try to access our translations with keys directly from the translation object. Here is an [article](https://webtips.dev/webtips/react-hooks/usetranslate-hook-in-react) with an example of using a custom useTranslate hook to access translated values. Let's implement this in our app:)

And last, but not least, let's store translated values in a JSON file. 🙂
<img width="607" alt="image" src="https://github.com/ffriday/graphiql-app/assets/29694535/bee1a7a0-a0ef-4a96-bd0e-1eeac662b735">

_Originally posted by @Yauhenia-Zhdanovich in https://github.com/ffriday/graphiql-app/pull/4#discussion_r1421779801_

### Tasks

- [ ] Fix typo in 'provisers' folder
- [ ] Organize file/context/provider names in the same style
- [ ] Replace current localization functions with useTranslate hook
